import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const indexPath = new URL("../src/index.js", import.meta.url);

async function source() {
  return readFile(indexPath, "utf8");
}

test("registers undo/redo tools", async () => {
  const src = await source();
  assert.match(src, /"undo"/);
  assert.match(src, /"redo"/);
});

test("registers fuzzy track tools", async () => {
  const src = await source();
  assert.match(src, /"find_track_by_name"/);
  assert.match(src, /"set_track_volume_by_name"/);
  assert.match(src, /"launch_clip_by_track_name"/);
});

test("registers render and dashboard tools", async () => {
  const src = await source();
  assert.match(src, /"render_project_audio"/);
  assert.match(src, /"render_stems"/);
  assert.match(src, /"get_metrics_dashboard"/);
});

test("registers action plan execution tools", async () => {
  const src = await source();
  assert.match(src, /"execute_action_plan"/);
  assert.match(src, /"get_allowed_plan_actions"/);
});

test("registers policy and profile tools", async () => {
  const src = await source();
  assert.match(src, /"get_policy_state"/);
  assert.match(src, /"set_policy_state"/);
  assert.match(src, /"render_with_profile"/);
  assert.match(src, /"write_device_automation_curve"/);
  assert.match(src, /OSC_ENDPOINT_VARIANTS/);
  assert.match(src, /"warmup_write_endpoints"/);
  assert.match(src, /"warmup_report_recommendations"/);
});

test("registers health and diagnostics tools", async () => {
  const src = await source();
  assert.match(src, /"health_live_test"/);
  assert.match(src, /"run_smoke_check"/);
  assert.match(src, /"get_protocol_diagnostics"/);
  assert.match(src, /"get_last_error"/);
  assert.match(src, /"set_safety_mode"/);
});

test("registers advanced scaffold tools", async () => {
  const src = await source();
  assert.match(src, /"get_ops_dashboard"/);
  assert.match(src, /"get_ops_dashboard_compact"/);
  assert.match(src, /"get_session_event_cache"/);
  assert.match(src, /"preflight_action_plan"/);
  assert.match(src, /"detect_capability_profile"/);
  assert.match(src, /"upsert_alias"/);
  assert.match(src, /"resolve_alias"/);
  assert.match(src, /"register_device_preset_alias"/);
  assert.match(src, /"list_alias_registry"/);
  assert.match(src, /"create_export_job"/);
  assert.match(src, /"run_export_job"/);
  assert.match(src, /"get_export_job"/);
  assert.match(src, /"list_export_jobs"/);
});

test("registers creative copilot expansion tools", async () => {
  const src = await source();
  assert.match(src, /"compile_musical_intent"/);
  assert.match(src, /"arrangement_intelligence"/);
  assert.match(src, /"run_mix_health_check"/);
  assert.match(src, /"apply_sound_design_macro"/);
  assert.match(src, /"generate_midi_phrase"/);
  assert.match(src, /"generate_drum_pattern"/);
  assert.match(src, /"compose_automation_helper"/);
  assert.match(src, /"performance_scene_action"/);
  assert.match(src, /"configure_live_safety_rails"/);
  assert.match(src, /"run_project_quality_checks"/);
  assert.match(src, /"reference_track_workflow"/);
  assert.match(src, /"export_batch_profiles"/);
  assert.match(src, /"set_user_preferences"/);
  assert.match(src, /"get_user_preferences"/);
  assert.match(src, /"ingest_voice_command"/);
  assert.match(src, /"semantic_plugin_control"/);
  assert.match(src, /"generate_collab_handoff"/);
  assert.match(src, /"explain_action_for_learning"/);
  assert.match(src, /"upsert_template_pack"/);
  assert.match(src, /"list_template_packs"/);
  assert.match(src, /"run_show_mode_checklist"/);
  assert.match(src, /"configure_external_hooks"/);
  assert.match(src, /"upsert_reactive_rule"/);
  assert.match(src, /"list_reactive_rules"/);
  assert.match(src, /"comp_take_assistant"/);
  assert.match(src, /"setup_sidechain_bus"/);
  assert.match(src, /"semantic_clip_edit"/);
  assert.match(src, /"harmony_arranger"/);
  assert.match(src, /"humanize_drums"/);
  assert.match(src, /"apply_fx_chain_template"/);
  assert.match(src, /"run_master_bus_guardrails"/);
  assert.match(src, /"prepare_stems_one_click"/);
  assert.match(src, /"session_diff_undo_bundle"/);
  assert.match(src, /"auto_scene_sequencer"/);
  assert.match(src, /"create_panic_macro"/);
  assert.match(src, /"run_macro"/);
  assert.match(src, /"record_prompt_macro"/);
  assert.match(src, /"project_cleanup_bot"/);
  assert.match(src, /"reference_match_assistant"/);
  assert.match(src, /"set_collaborator_mode"/);
  assert.match(src, /"task_linked_production_flow"/);
  assert.match(src, /"voice_live_mode_command"/);
  assert.match(src, /"plugin_preset_intelligence"/);
  assert.match(src, /"export_deliverables_matrix"/);
  assert.match(src, /"run_auto_mix_pass"/);
  assert.match(src, /"build_vocal_chain"/);
  assert.match(src, /"repair_clip_timing"/);
  assert.match(src, /"build_transition_between_sections"/);
  assert.match(src, /"shape_section_energy"/);
  assert.match(src, /"configure_adaptive_macro_performer"/);
  assert.match(src, /"auto_gain_stage_tracks"/);
  assert.match(src, /"create_bus_architecture"/);
  assert.match(src, /"set_latency_safe_recording_mode"/);
  assert.match(src, /"arrangement_completion_assistant"/);
  assert.match(src, /"detect_track_roles"/);
  assert.match(src, /"run_release_prep_pipeline"/);
  assert.match(src, /"smart_sample_audit"/);
  assert.match(src, /"schedule_macro_timeline"/);
  assert.match(src, /"configure_live_improv_guardrails"/);
  assert.match(src, /"diagnose_mix_issue"/);
  assert.match(src, /"optimize_plugin_chain"/);
  assert.match(src, /"set_session_goal"/);
  assert.match(src, /"manage_setlist"/);
  assert.match(src, /"export_session_documentation"/);
  assert.match(src, /"ai_arrangement_rewrite"/);
  assert.match(src, /"drum_replacement_assistant"/);
  assert.match(src, /"resolve_kick_bass_conflict"/);
  assert.match(src, /"advanced_vocal_polish"/);
  assert.match(src, /"transform_genre_template"/);
  assert.match(src, /"detect_section_similarity"/);
  assert.match(src, /"generate_drop_builder_plan"/);
  assert.match(src, /"write_dynamic_bus_automation"/);
  assert.match(src, /"run_release_readiness_score"/);
  assert.match(src, /"intelligent_freeze_manager"/);
  assert.match(src, /"set_session_focus_mode"/);
  assert.match(src, /"contextual_coaching_assistant"/);
  assert.match(src, /"rank_recording_takes"/);
  assert.match(src, /"reference_aware_tonal_targeting"/);
  assert.match(src, /"create_creative_prompt_scene"/);
  assert.match(src, /"live_performance_cue_engine"/);
  assert.match(src, /"error_recovery_autopilot"/);
  assert.match(src, /"set_project_memory_profile"/);
  assert.match(src, /"generate_release_variants"/);
  assert.match(src, /"run_post_export_qa"/);
  assert.match(src, /"normalize_stem_naming"/);
  assert.match(src, /"target_prerelease_loudness"/);
  assert.match(src, /"find_arrangement_gaps"/);
  assert.match(src, /"reinforce_hook_section"/);
  assert.match(src, /"optimize_kick_transient"/);
  assert.match(src, /"check_bass_mono_compatibility"/);
  assert.match(src, /"set_drum_bus_punch_mode"/);
  assert.match(src, /"score_vocal_intelligibility"/);
  assert.match(src, /"plan_scene_energy_curve"/);
  assert.match(src, /"restore_live_emergency_state"/);
  assert.match(src, /"manage_adaptive_sidechain"/);
  assert.match(src, /"detect_automation_conflicts"/);
  assert.match(src, /"set_device_parameter_lock_mode"/);
  assert.match(src, /"ear_training_prompt_mode"/);
  assert.match(src, /"monitor_session_drift"/);
  assert.match(src, /"run_variant_consistency_audit"/);
  assert.match(src, /"simulate_mix_translation"/);
  assert.match(src, /"batch_song_operations"/);
  assert.match(src, /"package_client_revision"/);
  assert.match(src, /"create_auto_rollback_policy"/);
  assert.match(src, /"run_gain_staging_autopilot"/);
  assert.match(src, /"run_phase_alignment_check"/);
  assert.match(src, /"run_masking_analysis"/);
  assert.match(src, /"manage_dynamic_range"/);
  assert.match(src, /"detect_sibilance_harshness"/);
  assert.match(src, /"run_low_end_control_suite"/);
  assert.match(src, /"optimize_bus_compression"/);
  assert.match(src, /"run_transient_shaping_assistant"/);
  assert.match(src, /"run_stereo_image_optimizer"/);
  assert.match(src, /"manage_reverb_delay_space"/);
  assert.match(src, /"run_automation_quality_check"/);
  assert.match(src, /"run_reference_match_engine"/);
  assert.match(src, /"run_master_chain_safety_scan"/);
  assert.match(src, /"run_mix_translation_diagnostics"/);
  assert.match(src, /"run_stem_quality_auditor"/);
  assert.match(src, /"optimize_clip_gain"/);
  assert.match(src, /"run_noise_floor_check"/);
  assert.match(src, /"run_loudness_workflow_assistant"/);
  assert.match(src, /"analyze_revision_delta"/);
  assert.match(src, /"run_engineering_checklist_mode"/);
  assert.match(src, /"plan_integrated_loudness_meter_path"/);
  assert.match(src, /"configure_true_peak_guardrails"/);
  assert.match(src, /"analyze_spectral_balance_fingerprint"/);
  assert.match(src, /"build_masking_map_v2"/);
  assert.match(src, /"enable_solo_safe_diagnostic_mode"/);
  assert.match(src, /"monitor_correlation_mono_sum"/);
  assert.match(src, /"plan_multiband_dynamics_chain"/);
  assert.match(src, /"generate_de_essing_automation_plan"/);
  assert.match(src, /"plan_vocal_rider"/);
  assert.match(src, /"suggest_parallel_processing_recipes"/);
  assert.match(src, /"manage_send_reverb_economy"/);
  assert.match(src, /"align_delay_coherence"/);
  assert.match(src, /"run_kick_bass_phase_lab"/);
  assert.match(src, /"build_drum_phase_alignment_pack"/);
  assert.match(src, /"apply_translation_presets"/);
  assert.match(src, /"build_headphone_translation_profile"/);
  assert.match(src, /"lock_master_chain_delta"/);
  assert.match(src, /"plan_stem_loudness_normalization"/);
  assert.match(src, /"generate_dynamic_range_report"/);
  assert.match(src, /"build_client_revision_ab_pack"/);
  assert.match(src, /"set_engineering_session_mode"/);
  assert.match(src, /"append_change_attribution_log"/);
  assert.match(src, /"run_blind_ab_helper"/);
  assert.match(src, /"plan_vocal_take_ladder"/);
  assert.match(src, /"plan_vocal_punch_in_session"/);
  assert.match(src, /"map_vocal_breath_noise_candidates"/);
  assert.match(src, /"run_vocal_room_tone_headphone_checklist"/);
  assert.match(src, /"run_vocal_comp_workflow_v2"/);
  assert.match(src, /"analyze_vocal_take_consistency"/);
  assert.match(src, /"plan_vocal_tuning_strategy"/);
  assert.match(src, /"plan_vocal_timing_tighten"/);
  assert.match(src, /"setup_vocal_doubles_stack"/);
  assert.match(src, /"plan_singer_plugin_chain"/);
  assert.match(src, /"run_pre_bounce_sibilance_check"/);
  assert.match(src, /"setup_warmup_then_record_scene"/);
  assert.match(src, /"generate_vocal_harmony_midi_scaffold"/);
  assert.match(src, /"setup_backing_vocal_bus"/);
  assert.match(src, /"configure_singer_warmup_metronome"/);
  assert.match(src, /"export_lyric_cue_sheet_from_clips"/);
  assert.match(src, /"run_vocal_ear_training_checklist"/);
  assert.match(src, /"manage_vocal_fx_snapshots"/);
  assert.match(src, /"audit_vocal_monitor_path_safety"/);
  assert.match(src, /"configure_vocal_setlist_scenes"/);
  assert.match(src, /"plan_vocal_delivery_variants"/);
  assert.match(src, /"plan_vocal_stem_export_naming"/);
  assert.match(src, /"plan_vocal_chain_ab_snapshots"/);
  assert.match(src, /"run_low_latency_vocal_tracking_checklist"/);
  assert.match(src, /"plan_duet_harmony_recording_session"/);
  assert.match(src, /"run_vocal_booth_session_start_macro"/);
  assert.match(src, /"plan_vocal_adlib_lane"/);
  assert.match(src, /"plan_vocal_tone_modes_scenes"/);
  assert.match(src, /"plan_choir_stack_builder"/);
  assert.match(src, /"plan_melody_to_midi_capture_workflow"/);
  assert.match(src, /"run_vocal_pitch_vibrato_analysis_placeholder"/);
  assert.match(src, /"run_vocal_breath_detector_v2_placeholder"/);
  assert.match(src, /"run_vocal_range_report_session"/);
  assert.match(src, /"sync_producer_singer_revision_notes"/);
  assert.match(src, /"plan_vocal_pronunciation_diction_guide"/);
  assert.match(src, /"run_vocal_health_fatigue_guard"/);
  assert.match(src, /"suggest_song_key_from_session_midi"/);
  assert.match(src, /"plan_lead_tuned_vs_raw_stem_matrix"/);
  assert.match(src, /"plan_sync_picture_vocal_cues"/);
  assert.match(src, /"upsert_arrangement_section"/);
  assert.match(src, /"list_arrangement_sections"/);
  assert.match(src, /"export_arrangement_sections"/);
  assert.match(src, /"import_arrangement_sections"/);
  assert.match(src, /"save_arrangement_section_profile"/);
  assert.match(src, /"load_arrangement_section_profile"/);
  assert.match(src, /"clone_arrangement_section_map"/);
  assert.match(src, /"list_arrangement_section_profiles"/);
  assert.match(src, /"delete_arrangement_section_profile"/);
  assert.match(src, /"delete_arrangement_section"/);
});
